from utils.utils import *
import os 
import json
import numpy as np
import argparse
from datasets import load_dataset
import time
def deepseek_query(client,messages):
        response = client.chat.completions.create(
        model="deepseek-chat",
        messages=messages,
        stream=False)
        return response.choices[0].message.content
  
def gpt_query(client,messages):
    response = client.chat.completions.create(
    model="gpt-4o",
    messages=messages,
    stream=False)
    return response.choices[0].message.content




        
def main():
    t0 = time.time()
    dataset_name =['gsm8k','game24','piqa','commonsense']
    json_lst = []
    for name in dataset_name:
        with open('./input_data/qa_dataset_'+name+'.json', 'r') as file:
            data = json.load(file)
            json_lst.append(data)
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--api", 
        type=str, 
        default='deepseek', 
        help="API agent"
    )
    parser.add_argument(
        "--output", 
        type=str, 
        default="./output.md", 
        help="Path to the output file (default: output.txt)."
    )
    parser.add_argument(
        "--dataset", 
        type=str,
        default='pubmed',
        help="Enable verbose mode."
    )
    parser.add_argument(
        "--index", 
        type=int,
        default=0,
        help="question index to be chosen"
    )
    
    
    message = []
    message.append({'role':'system','content':system_prompt})
    for i in range(len(dataset_name)):
        data = json_lst[i]
        idx = np.random.randint(0,len(data)-1,3)
        message.append({'role':'user','content':'Okay I will feed you with the questions from dataset'+ dataset_name[i]+'. And I will show you what is the best answer to each question along with its reasoning style.'})
    for id in idx:
        question=data[id]['question']
        message.append({'role':'system','content':'Here is one example from dataset'+dataset_name[i]+'. And the question is: '+ question})
        best_answer = data[id]['best']
        answer= data[id][best_answer][0]
        message.append({'role':'user','content':'Using the reasoning style '+ best_answer+' we can achieve the best answer. And here is the answer: '+ answer })

    
    
    args = parser.parse_args()
    client = initialize_client(args.api)
    if args.dataset == 'pubmed':
        ds = load_dataset("qiaojin/PubMedQA", "pqa_labeled")
        index = args.index
        question = ds['train'][index]['question']
        context = ds['train'][index]['context']['contexts'][0]
        final_decison = ds['train'][index]['final_decision']
        long_answer = ds['train'][index]['long_answer']
        message.append({'role':'system','content':'Now with the examples given above, try to generate answer given a new prompt given here. You are about to finish a new task solving operation research question given below. And the context of the question is: '+ context })
        message.append({'role':'user','content':question+'state your choice of reasoning style. Try to discover new reasoning style.'})   
        response = deepseek_query(client,message)
        print(response)
        responses_oT = {}
        for style in thinking_styles:
            message_style = []
            message_style.append({'role':'system','content':'Now with the examples given above, try to generate answer given a new prompt given here. You are about to finish a new task solving operation research question given below. And the context of the question is: '+ context+'Use the thinking style: '+style+'. Which is described as: '+ thinking_styles[style] })
            message_style.append({'role':'user','content':question})   
            responses_oT[style] = deepseek_query(client, message_style)
            print(style + "  finished")
            print("-"*10)
        
        message_evaluate = [{'role':'system','content':'Now evaluate the response to the question '+ question+'And a reference answer to this question is given as: '+ 'final decision: '+ final_decison+'. Long answer: '+ long_answer},
                    {'role':'user', 'content':'Evaluate this answer: '+ response+ 'Just tell me whether this answer is right or wrong.'},
                    {'role':'user', 'content':'Also compare this response to three answers generated by CoT: '+ responses_oT['CoT']+ 'AoT: '+ responses_oT['AoT']+'And ToT: '+ responses_oT['ToT']+'Among all the responses, tell me which response is the best.'}]
        response_evaluate = deepseek_query(client,message_evaluate)
        #output the file to md file
        with open(args.output, "a", encoding="utf-8") as f:
            f.write(question+'\n')
            f.write('Reference Answer: '+ final_decison+ '. Long Answer: '+ long_answer+'\n')
            f.write('## Meta Response\n')
            f.write(response+'\n')
            f.write('-'*10+'\n')
            for style in thinking_styles.keys():
                f.write("## "+ style+"\n")
                f.write(responses_oT[style]+'\n')
                f.write('-'*10+'\n')
            
            f.write('## Evaluate all responses \n')
            f.write(response_evaluate+'\n')
            f.write('-'*10+'\n')
    
        
    
    elif args.dataset == 'or3k':
        ds = load_dataset("CardinalOperations/OR-Instruct-Data-3K")
        index = args.index
        question = ds['train'][index]['prompt']
        answer = ds['train'][index]['completion']
        message.append({'role':'system','content':'Now with the examples given above, try to generate answer given a new prompt given here. You are about to finish a new task solving operation research question given below.'})
        message.append({'role':'user','content':question+'state your choice of reasoning style. Try to discover new reasoning style.'})   
        response = deepseek_query(client,message)
        print(response)
        responses_oT = {}
        for style in thinking_styles:
            message_style = []
            message_style.append({'role':'system','content':'Now with the examples given above, try to generate answer given a new prompt given here. You are about to finish a new task solving operation research question given below. And the context of the question is to solve operation research related questions. '+'Use the thinking style: '+style+'. Which is described as: '+ thinking_styles[style] })
            message_style.append({'role':'user','content':question})   
            responses_oT[style] = deepseek_query(client, message_style)
            print(style + "  finished")
            print("-"*10)
        message_evaluate = [{'role':'system','content':'Now evaluate the response to the question '+ question+'And a reference answer to this question is given as: '+ answer},
                    {'role':'user', 'content':'Evaluate this answer: '+ response+ 'Just tell me whether this answer is right or wrong.'},
                    {'role':'user', 'content':'Also compare this response to three answers generated by CoT: '+ responses_oT['CoT']+ 'AoT: '+ responses_oT['AoT']+'And ToT: '+ responses_oT['ToT']+'Among all the responses, tell me which response is the best.'}]
        response_evaluate = deepseek_query(client,message_evaluate)
        with open(args.output, "a", encoding="utf-8") as f:
            f.write(question+'\n')
            f.write('Reference Answer: \n '+ answer+'\n')
            f.write('## Meta Response\n')
            f.write(response+'\n')
            f.write('-'*10+'\n')
            for style in thinking_styles.keys():
                f.write("## "+ style+"\n")
                f.write(responses_oT[style]+'\n')
                f.write('-'*10+'\n')
            
            f.write('## Evaluate all responses \n')
            f.write(response_evaluate+'\n')
            f.write('-'*10+'\n')
        
    elif args.dataset == 'ormawps':
        index = args.index
        dataset = load_dataset("mwpt5/MAWPS")['train']
        question = dataset[index]['Question']
        answer = dataset[index]['Answer']
        equation = dataset[index]['Equation']
        number = dataset[index]['Numbers']
        message.append({'role':'system','content':'Now with the examples given above, try to generate answer given a new prompt given here. You are about to finish a new task solving math question given below.'})
        message.append({'role':'user','content':question+'state your choice of reasoning style. Try to discover new reasoning style.'+'Also the number values are given here '+ number})   
        response = deepseek_query(client,message)
        responses_oT = {}
        for style in thinking_styles:
            message_style = []
            message_style.append({'role':'system','content':'Now with the examples given above, try to generate answer given a new prompt given here. You are about to finish a new task solving operation research question given below. And the context of the question is to solve operation research related questions. '+'Use the thinking style: '+style+'. Which is described as: '+ thinking_styles[style] })
            message_style.append({'role':'user','content':question+'The numbers are given as: '+ number})   
            responses_oT[style] = deepseek_query(client, message_style)
            print(style + "  finished")
            print("-"*10)
        
        message_evaluate = [{'role':'system','content':'Now evaluate the response to the question '+ question+'The values for the number symbols in the question are given as'+number+'And a reference equation to this question is given as: '+ equation+'using the number given the answer is: '+ str(number) },
                    {'role':'user', 'content':'Evaluate this answer: '+ response+ 'Just tell me whether this answer is right or wrong.'},
                    {'role':'user', 'content':'Also compare this response to three answers generated by CoT: '+ responses_oT['CoT']+ 'AoT: '+ responses_oT['AoT']+'And ToT: '+ responses_oT['ToT']+'Among all the responses, tell me which response is the best.'}]
        response_evaluate = deepseek_query(client,message_evaluate)
        with open(args.output, "a", encoding="utf-8") as f:
            f.write(question+'\n')
            f.write('Reference Answer: \n '+ equation+'\n'+str(answer)+'\n')
            f.write('## Meta Response\n')
            f.write(response+'\n')
            f.write('-'*10+'\n')
            for style in thinking_styles.keys():
                f.write("## "+ style+"\n")
                f.write(responses_oT[style]+'\n')
                f.write('-'*10+'\n')
            
            f.write('## Evaluate all responses \n')
            f.write(response_evaluate+'\n')
            f.write('-'*10+'\n')
        
    else:
        raise ValueError("Wrong type of dataset")
    
    
    
    t1 = time.time()
    print("The implementation takes {} seconds".format(t1-t0))
    
    
    
        



if __name__ == "__main__":
    main()


